### ISSUE TITLE
@keyframe at-rule is not working

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1024]
### Description

The CSS compiler apply the selector scoping to the `@keyframes` at rules, making `@keyframe` currently unusable in LWC.

```css
/* Original */
@keyframes slide {
  from { margin-left: 100%; }
  to { margin-left: 0%; }
}

/* Compiled */
@keyframes slide {
  from[c-app_app] {margin-left: 100%;}
  to[c-app_app] {margin-left: 0%;}
}
```

The `@keyframe` selector should stay untouched.

### Version
- LWC: 0.35.5
