### ISSUE TITLE
Animations are being overridden in Salesforce org

### ISSUE THREAD

**Issue by Blue-Hoopoe** [salesforce/lwc#1416]
### Description
When defining two LWC inisde a Salesforce org that are defining two CSS animations with the same name, one is always overridden by other. This is because `<style>` tags for both components are being placed in the same (global) scope. 

#### Steps to Reproduce

1. Log in to Salesforce org.
2. Create an Lightning Application (Aura).
3. Create two independent LWC components with the same CSS animation name.
4. Place them in a application from step 2.

**2. application.app**
``` html
<aura:application >
    <c:animationOne></c:animationOne>
    <c:animationTwo></c:animationTwo>
</aura:application>
```

**3a. animation-one.html**
``` html
<template>
    <h1>Animation One</h1>
</template>
```

**3a. animation-one.css**
``` css
@keyframes colored {
    0% { color: red; }
    100% { color: black; }
}

h1 {
    animation: colored .3s ease-in-out infinite alternate;
}
```

**3b. animation-two.html**
``` html
<template>
    <h1>Animation Two</h1>
</template>
```

**3a. animation-two.css**
``` css
@keyframes colored {
    0% { color: green; }
    100% { color: gold; }
}

h1 {
    animation: colored .3s ease-in-out infinite alternate;
}
```

#### Expected Results
The first ```<h1>``` tag in application should transition from red to black, while the second from green to gold.

#### Actual Results
Both```<h1>``` tags are transitioning from green to gold.

#### Additional info
It works as planned when using a standalone version of LWC. 
It breaks in the playground and in SF org.
