### ISSUE TITLE
Lightning tree grid missing padding-left after 20th level

### ISSUE THREAD

**Issue by fgl27** [salesforce/lwc#3024]
### Description
I have created a tree with a lot of levels, after level 20 there is no padding left:

On bellow img it row is a child of the row above, as one can see all accordions are open but the padding is missing after the 20th level

![image](https://user-images.githubusercontent.com/13755892/186468568-45ba538d-bbc3-4bac-bf3a-d674b090c0a4.png)

I check the css that the page loads and the last "aria-level" I can find is 20:

```css
[aria-level="20"]>.slds-tree__item {
    padding-left: 20rem
}

.slds-table_tree [aria-level="20"]>.slds-tree__item,
.slds-table--tree [aria-level="20"]>.slds-tree__item {
    padding-left: 20.5rem
}
```

#### Steps to Reproduce
Create a tree grid with more than 20 levels

bellow file contains the code, if I past here the 20+ levels will be hard to see.
[location.zip](https://github.com/salesforce/lwc/files/9417916/location.zip)

#### Expected Results
proper padding

#### Actual Results
missing padding

### Browsers Affected
Chrome, I assume all.

### Version
Salesforce Winter '22

**Possible Solution**
NA

**Additional context/Screenshots**
NA
