### ISSUE TITLE
CSS whitespace is considered significant for pseudo-elements

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3051]
### Description

For style scoping (e.g. synthetic shadow), the following CSS:

```css
*,
 ::before,
 ::after {
  box-sizing: border-box;
}
```

_should_ be compiled to:

```css
*[x-app_app],
[x-app_app]::before,
[x-app_app]::after {
  box-sizing: border-box;
}
```

...but instead it's compiled to:

```css
*[x-app_app],
[x-app_app] ::before,
[x-app_app] ::after {
  box-sizing: border-box;
}
```

Note the additional space before the `::before` and `::after`. If you remove the spaces in the source code, the problem goes away.

This is not only technically incorrect (and could lead to incorrect styling on descendants), but it's also a slight perf hit because the selector potentially matches more elements than otherwise.

#### Steps to Reproduce

[Repro](https://stackblitz.com/edit/salesforce-lwc-8ezshr?file=src/modules/x/app/app.css)
