### ISSUE TITLE
Style scoping transform doesn't support empty pseudo classes

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#307]
Today, the following pseudo-class doesn't get scoped at all.

```css
:nth-child(1n) {
 color: red;
}
```
