### ISSUE TITLE
2.45.3 @lwc/rollup-plugin breaks Yarn PnP

### ISSUE THREAD

**Issue by cvharris** [salesforce/lwc#3540]
Upgrading to version 2.45.3 from 2.45.2, something seems to have changed with how the dependencies are chained together. Yarn produces these errors if you're using PnP:

```
[!] Error: @lwc/rollup-plugin tried to access postcss-value-parser, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

These are sometimes small breaking changes, and the fix is typically to add them to `packageExtensions` in .yarnrc.yml, but this time it creates an incredibly long dependency chain...I gave up and opened this bug after this point:

```yml
packageExtensions:
  "@lwc/rollup-plugin@*":
    dependencies:
      "@lwc/compiler": "*"
      "postcss-value-parser": "*"
      "postcss-selector-parser": "*"
      "string.prototype.matchall": "*"
      "parse5": "^6"
      "he": "*"
      "estree-walker": "^2"
      "acorn": "^8"
      "astring": "^1"
```

Previously I only had to this (which may also be a dependency issue but isn't so bad:
```yml
packageExtensions:
  "@lwc/rollup-plugin@*":
    dependencies:
      "@lwc/compiler": "*"
```

But all those other ones suddenly being necessary feels like something small changed that wasn't intended to.
