### ISSUE TITLE
`:host` CSS selector is translated based on filesystem instead of runtime environment

### ISSUE THREAD

**Issue by fredboyle** [salesforce/lwc#383]
### Description

`interop:` namespace components incorrectly translate the `:host` CSS selector. The selector is converted based on the filesystem and not the intended runtime value of the lightning namespace.

#### Steps to Reproduce

Add a CSS file to any `interop:` component that contains a `:host` selector.

CSS file contents:
```css
:host {
    display: block;
}

a {
    color: red;
    border: 1px solid blue;
}
```

Currently rendered styles example:

#### Expected Results
```css
<style type="text/css" data-token="lightning-menu-item_menu-item">lightning-menu-item[interop-menu-item_menu-item],[is="lightning-menu-item"][lightning-menu-item_menu-item] {
    display: block;
}

a[lightning-menu-item_menu-item] {
    color: red;
    border: 1px solid blue;
}
</style>
```

#### Actual Results
```css
<style type="text/css" data-token="interop-menu-item_menu-item">interop-menu-item[interop-menu-item_menu-item],[is="interop-menu-item"][interop-menu-item_menu-item] {
    display: block;
}

a[interop-menu-item_menu-item] {
    color: red;
    border: 1px solid blue;
}
</style>
```

### Browsers Affected
ALL

### Version
- LWC: 0.20.x & 0.22.5
