### ISSUE TITLE
CSS Parser does not support # character

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#530]
#### Steps to Reproduce

Found this one in the todo-mvc css when trying to move the css to the component.

```css
.todo-list .li .toggle + label {
	/*
		Firefox requires the hash to be escaped - https://bugzilla.mozilla.org/show_bug.cgi?id=922433
		IE and Edge requires *everything* to be escaped to render, so we do that instead of just the hash - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7157459/
	*/
	background-image: url('data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%2240%22%20height%3D%2240%22%20viewBox%3D%22-10%20-18%20100%20135%22%3E%3Ccircle%20cx%3D%2250%22%20cy%3D%2250%22%20r%3D%2250%22%20fill%3D%22none%22%20stroke%3D%22%23ededed%22%20stroke-width%3D%223%22/%3E%3C/svg%3E');
	background-repeat: no-repeat;
	background-position: center left;
}
```

#### Expected Results

It should compile.

#### Actual Results

```bash
[0] rollup v0.63.4
[0] bundles /Users/cpatino/repo/lwc-todomvc/src/main.js → public/js/main.js...
[0] [!] Error: Unexpected character '#'
[0] src/todo/item/item.css (157:20)
[0] 155:   /*
[0] 156:     Firefox requires `#` to be escaped - https://bugzilla.mozilla.org/show_bug.cgi?id=922433
[0] 157:     IE and Edge requires *everything* to be escaped to render, so we do that instead of just the `#` - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7157459/
[0]                            ^
[0] 158:   */
[0] 159:   background-image: url('data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20width%3D%2240%22%20height%3D%2240%22%20viewBox%3D%22-10%20-18%20100%20135%22%3E%3Ccircle%20cx%3D%2250%22%20cy%3D%2250%22%20r%3D%2250%22%20fill%3D%22none%22%20stroke%3D%22%23ededed%22%20stroke-width%3D%223%22/%3E%3C/svg%3E');
[0]
[0] 1
error Command failed with exit code 1.
```
