### ISSUE TITLE
Usage z-index in component template is optimized to aggressively when minified

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#689]
### Description

Currently, the compiler when the `minify` flag is set to `true`, the compiler optimize the `z-index` by rebasing them from `1`.

```css
/* Before */
h1 { z-index: 100; } 
h2 { z-index: 500; }

/* After */
h1 { z-index: 1; } 
h2 { z-index: 2; }
```

However, this transformation doesn't work when multiple styles coexist on the same page. We need to disable the z-index optimization in prod.
