### ISSUE TITLE
LWC style compiler serialize properly declaration with customProperties config is set

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#855]
### Description

The lwc-style-compiler doesn't serialize properly style declaration when the `customProperties.resolverModule` config is set. For example: 
* the `!important` marked is dropped from the generated style
* the line return and whitespaces are not preserved

#### Steps to Reproduce

```css
div {
	color: var(--color, blue) !important;
}
```

#### Expected Results

```css
div {
	color: var(--color, blue) !important;
}
```

#### Actual Results

```css
div {color: var(--color, blue);}
```

### Browsers Affected
All browsers

### Version
- LWC: 0.33.7

## Possible Solution

The [serialize.ts](https://github.com/salesforce/lwc/blob/master/packages/lwc-style-compiler/src/serialize.ts#L289-L298) doesn't take into account the information stored on the `node.raws` property. When doing a custom serialization the formatting information should be extracted from the `raws` object. We should replicate the logic from the [default stringifier](https://github.com/postcss/postcss/blob/master/lib/stringifier.es6#L39-L49).
